### ISSUE TITLE
Basic Hub on Arduino

### ISSUE THREAD

**Issue by konnorandrews** [USU-Robosub/submarine#15]
## New feature request

The Arduino needs a basic hub to receive messages over serial.

#### Requirements

- [x] Add a `Hub` class to the Arduino project.
##### The `Hub` class
- [x] has the method `void Hub.poll()` that reads a single event from serial and executes the corresponding controller. This should block.
- [x] the `Hub.poll()` method checks that the first `long` read from serial is `0000`. If it is not the message has been corrupted and the hub should execute the `controllers[0]` controller to perform a buffer purge.
- [x] has the method `void Hub.emit(long name, long* data, long length)` that writes the data to serial.
- [x] should have a constructor that accepts an array of `Controller`. 

#### Other thoughts

Hub interface:
```cpp
class Hub{
public:
  Hub(Controller* controllers);
  void poll();
  void emit(long name, long* data long length);
private:
  long readOneLong();
  writeOneLong(long value);
} ;
```

Controller interface:
```cpp
class Controller{
public:
  virtual void execute(Hub* hub, long* data, long length);
} ;
```

Event message protocol reference:
```
[null] [name] [length] [data #1] [data #2] [data #3] ...
0000 001A 0003 04A8 1321 8765
```

**Comment by TJonesy** [comment]
Might it be better to use a hash instead of just 0000?

**Comment by TJonesy** [comment]
It might also be good to know how many controllers there are so we can validate the command that is coming over the serial.
